/**
 * Asma-ul-Husna — The 99 Beautiful Names of Allah
 * arabic: Arabic script  ·  trans: transliteration
 * en: English meaning    ·  bn: বাংলা অর্থ
 */
export const ASMAUL_HUSNA = [
  { id: 1,  arabic: 'الله',              trans: 'Allah',              en: 'The Greatest Name / The One True God',     bn: 'আল্লাহ — একমাত্র সত্য মাবুদ' },
  { id: 2,  arabic: 'الرَّحْمَٰن',        trans: 'Ar-Rahman',          en: 'The Most Compassionate',                    bn: 'পরম করুণাময়' },
  { id: 3,  arabic: 'الرَّحِيم',          trans: 'Ar-Rahim',           en: 'The Most Merciful',                         bn: 'অতি দয়ালু' },
  { id: 4,  arabic: 'الْمَلِك',           trans: 'Al-Malik',           en: 'The King / The Sovereign Lord',             bn: 'প্রকৃত অধিপতি, মহারাজাধিরাজ' },
  { id: 5,  arabic: 'الْقُدُّوس',         trans: 'Al-Quddus',          en: 'The Most Holy, The Pure',                   bn: 'পরম পবিত্র' },
  { id: 6,  arabic: 'السَّلَام',          trans: 'As-Salam',           en: 'The Source of Peace',                       bn: 'শান্তিদাতা' },
  { id: 7,  arabic: 'الْمُؤْمِن',         trans: 'Al-Mu\'min',         en: 'The Giver of Faith and Security',           bn: 'নিরাপত্তা দানকারী' },
  { id: 8,  arabic: 'الْمُهَيْمِن',       trans: 'Al-Muhaymin',        en: 'The Guardian, The Protector',               bn: 'রক্ষণাবেক্ষণকারী' },
  { id: 9,  arabic: 'الْعَزِيز',          trans: 'Al-Aziz',            en: 'The Almighty, The Mighty',                  bn: 'পরাক্রমশালী' },
  { id: 10, arabic: 'الْجَبَّار',         trans: 'Al-Jabbar',          en: 'The Compeller, The Restorer',               bn: 'মহাপ্রতাপশালী' },
  { id: 11, arabic: 'الْمُتَكَبِّر',      trans: 'Al-Mutakabbir',      en: 'The Supreme, The Majestic',                 bn: 'মহিমান্বিত, অহংকারের অধিকারী' },
  { id: 12, arabic: 'الْخَالِق',          trans: 'Al-Khaliq',          en: 'The Creator',                               bn: 'সৃষ্টিকর্তা' },
  { id: 13, arabic: 'الْبَارِئ',          trans: 'Al-Bari\'',          en: 'The Evolver, The Maker',                    bn: 'নিখুঁত স্রষ্টা' },
  { id: 14, arabic: 'الْمُصَوِّر',        trans: 'Al-Musawwir',        en: 'The Fashioner, The Shaper',                 bn: 'রূপদানকারী' },
  { id: 15, arabic: 'الْغَفَّار',         trans: 'Al-Ghaffar',         en: 'The Repeatedly Forgiving',                  bn: 'বার বার ক্ষমাকারী' },
  { id: 16, arabic: 'الْقَهَّار',         trans: 'Al-Qahhar',          en: 'The Subduer, The Dominant',                 bn: 'পরাক্রমশালী বিজয়ী' },
  { id: 17, arabic: 'الْوَهَّاب',         trans: 'Al-Wahhab',          en: 'The Bestower',                              bn: 'দানশীল' },
  { id: 18, arabic: 'الرَّزَّاق',         trans: 'Ar-Razzaq',          en: 'The Provider, The Sustainer',               bn: 'রিযিকদাতা' },
  { id: 19, arabic: 'الْفَتَّاح',         trans: 'Al-Fattah',          en: 'The Opener, The Judge',                     bn: 'বিজয়দানকারী, মীমাংসাকারী' },
  { id: 20, arabic: 'الْعَلِيم',          trans: 'Al-\'Alim',          en: 'The All-Knowing',                           bn: 'সর্বজ্ঞ' },
  { id: 21, arabic: 'الْقَابِض',          trans: 'Al-Qabid',           en: 'The Withholder, The Constrictor',           bn: 'সংকোচনকারী' },
  { id: 22, arabic: 'الْبَاسِط',          trans: 'Al-Basit',           en: 'The Extender, The Expander',                bn: 'প্রসারণকারী' },
  { id: 23, arabic: 'الْخَافِض',          trans: 'Al-Khafid',          en: 'The Abaser, The Reducer',                   bn: 'অবনতকারী' },
  { id: 24, arabic: 'الرَّافِع',          trans: 'Ar-Rafi\'',          en: 'The Exalter, The Elevator',                 bn: 'উন্নতকারী' },
  { id: 25, arabic: 'الْمُعِزّ',          trans: 'Al-Mu\'izz',         en: 'The Giver of Honor',                        bn: 'সম্মানদানকারী' },
  { id: 26, arabic: 'الْمُذِلّ',          trans: 'Al-Mudhill',         en: 'The Giver of Dishonor',                     bn: 'অপমানকারী' },
  { id: 27, arabic: 'السَّمِيع',          trans: 'As-Sami\'',          en: 'The All-Hearing',                           bn: 'সর্বশ্রোতা' },
  { id: 28, arabic: 'الْبَصِير',          trans: 'Al-Basir',           en: 'The All-Seeing',                            bn: 'সর্বদ্রষ্টা' },
  { id: 29, arabic: 'الْحَكَم',           trans: 'Al-Hakam',           en: 'The Judge, The Arbitrator',                 bn: 'বিচারক' },
  { id: 30, arabic: 'الْعَدْل',           trans: 'Al-\'Adl',           en: 'The Utterly Just',                          bn: 'ন্যায়পরায়ণ' },
  { id: 31, arabic: 'اللَّطِيف',          trans: 'Al-Latif',           en: 'The Subtle, The Gentle',                    bn: 'সূক্ষ্মদর্শী, পরম দয়ালু' },
  { id: 32, arabic: 'الْخَبِير',          trans: 'Al-Khabir',          en: 'The All-Aware',                             bn: 'সর্ববিষয়ে অবগত' },
  { id: 33, arabic: 'الْحَلِيم',          trans: 'Al-Halim',           en: 'The Forbearing, The Indulgent',             bn: 'সহনশীল' },
  { id: 34, arabic: 'الْعَظِيم',          trans: 'Al-\'Azim',          en: 'The Magnificent, The Supreme',              bn: 'মহান' },
  { id: 35, arabic: 'الْغَفُور',          trans: 'Al-Ghafur',          en: 'The Forgiving',                             bn: 'ক্ষমাশীল' },
  { id: 36, arabic: 'الشَّكُور',          trans: 'Ash-Shakur',         en: 'The Most Appreciative',                     bn: 'গুণগ্রাহী' },
  { id: 37, arabic: 'الْعَلِيّ',          trans: 'Al-\'Ali',           en: 'The Most High',                             bn: 'সর্বোচ্চ' },
  { id: 38, arabic: 'الْكَبِير',          trans: 'Al-Kabir',           en: 'The Greatest, The Most Great',              bn: 'মহত্তম' },
  { id: 39, arabic: 'الْحَفِيظ',          trans: 'Al-Hafiz',           en: 'The Preserver',                             bn: 'সংরক্ষণকারী' },
  { id: 40, arabic: 'الْمُقِيت',          trans: 'Al-Muqit',           en: 'The Sustainer, The Nourisher',              bn: 'অন্নদাতা' },
  { id: 41, arabic: 'الْحَسِيب',          trans: 'Al-Hasib',           en: 'The Reckoner',                              bn: 'হিসাবগ্রহণকারী' },
  { id: 42, arabic: 'الْجَلِيل',          trans: 'Al-Jalil',           en: 'The Majestic',                              bn: 'মহিমান্বিত' },
  { id: 43, arabic: 'الْكَرِيم',          trans: 'Al-Karim',           en: 'The Most Generous, The Bountiful',          bn: 'মহানুভব, দয়ালু' },
  { id: 44, arabic: 'الرَّقِيب',          trans: 'Ar-Raqib',           en: 'The Watchful',                              bn: 'প্রহরী' },
  { id: 45, arabic: 'الْمُجِيب',          trans: 'Al-Mujib',           en: 'The Responsive, The Answerer of prayers',   bn: 'দোয়া কবুলকারী' },
  { id: 46, arabic: 'الْوَاسِع',          trans: 'Al-Wasi\'',          en: 'The All-Encompassing, The Vast',            bn: 'সর্বব্যাপী' },
  { id: 47, arabic: 'الْحَكِيم',          trans: 'Al-Hakim',           en: 'The All-Wise',                              bn: 'প্রজ্ঞাময়' },
  { id: 48, arabic: 'الْوَدُود',          trans: 'Al-Wadud',           en: 'The Most Loving',                           bn: 'প্রেমময়' },
  { id: 49, arabic: 'الْمَجِيد',          trans: 'Al-Majid',           en: 'The Glorious, The Most Honorable',          bn: 'গৌরবময়' },
  { id: 50, arabic: 'الْبَاعِث',          trans: 'Al-Ba\'ith',         en: 'The Resurrector',                           bn: 'পুনরুত্থানকারী' },
  { id: 51, arabic: 'الشَّهِيد',          trans: 'Ash-Shahid',         en: 'The Witness',                               bn: 'সাক্ষী' },
  { id: 52, arabic: 'الْحَقّ',            trans: 'Al-Haqq',            en: 'The Absolute Truth',                        bn: 'চিরসত্য' },
  { id: 53, arabic: 'الْوَكِيل',          trans: 'Al-Wakil',           en: 'The Trustee, The Disposer of Affairs',      bn: 'কর্মবিধায়ক' },
  { id: 54, arabic: 'الْقَوِيّ',          trans: 'Al-Qawiyy',          en: 'The Most Strong',                           bn: 'পরম শক্তিশালী' },
  { id: 55, arabic: 'الْمَتِين',          trans: 'Al-Matin',           en: 'The Firm, The Steadfast',                   bn: 'সুদৃঢ়' },
  { id: 56, arabic: 'الْوَلِيّ',          trans: 'Al-Waliyy',          en: 'The Protecting Friend',                     bn: 'অভিভাবক, বন্ধু' },
  { id: 57, arabic: 'الْحَمِيد',          trans: 'Al-Hamid',           en: 'The Praiseworthy',                          bn: 'প্রশংসিত' },
  { id: 58, arabic: 'الْمُحْصِي',         trans: 'Al-Muhsi',           en: 'The All-Enumerating, The Counter',          bn: 'গণনাকারী' },
  { id: 59, arabic: 'الْمُبْدِئ',         trans: 'Al-Mubdi\'',         en: 'The Originator, The Initiator',             bn: 'প্রথম সৃষ্টিকারী' },
  { id: 60, arabic: 'الْمُعِيد',          trans: 'Al-Mu\'id',          en: 'The Restorer, The Reproducer',              bn: 'পুনঃসৃষ্টিকারী' },
  { id: 61, arabic: 'الْمُحْيِي',         trans: 'Al-Muhyi',           en: 'The Giver of Life',                         bn: 'জীবনদাতা' },
  { id: 62, arabic: 'الْمُمِيت',          trans: 'Al-Mumit',           en: 'The Creator of Death',                      bn: 'মৃত্যুদাতা' },
  { id: 63, arabic: 'الْحَيّ',            trans: 'Al-Hayy',            en: 'The Ever-Living',                           bn: 'চিরঞ্জীব' },
  { id: 64, arabic: 'الْقَيُّوم',         trans: 'Al-Qayyum',          en: 'The Self-Subsisting, Sustainer of all',     bn: 'চিরস্থায়ী, ধারক' },
  { id: 65, arabic: 'الْوَاجِد',          trans: 'Al-Wajid',           en: 'The Finder, The Perceiver',                 bn: 'প্রাপ্তিদাতা' },
  { id: 66, arabic: 'الْمَاجِد',          trans: 'Al-Majid',           en: 'The Illustrious, The Noble',                bn: 'মহানুভব, সম্মানিত' },
  { id: 67, arabic: 'الْوَاحِد',          trans: 'Al-Wahid',           en: 'The One, The Unique',                       bn: 'এক, অদ্বিতীয়' },
  { id: 68, arabic: 'الصَّمَد',           trans: 'As-Samad',           en: 'The Eternal, The Self-Sufficient Master',   bn: 'অমুখাপেক্ষী, চিরঅমর' },
  { id: 69, arabic: 'الْقَادِر',          trans: 'Al-Qadir',           en: 'The All-Powerful, The Capable',             bn: 'সর্বশক্তিমান' },
  { id: 70, arabic: 'الْمُقْتَدِر',       trans: 'Al-Muqtadir',        en: 'The Creator of all Power',                  bn: 'পূর্ণ ক্ষমতাবান' },
  { id: 71, arabic: 'الْمُقَدِّم',        trans: 'Al-Muqaddim',        en: 'The Expediter, The Promoter',               bn: 'অগ্রবর্তীকারী' },
  { id: 72, arabic: 'الْمُؤَخِّر',        trans: 'Al-Mu\'akhkhir',     en: 'The Delayer',                               bn: 'বিলম্বকারী' },
  { id: 73, arabic: 'الْأَوَّل',          trans: 'Al-Awwal',           en: 'The First',                                 bn: 'প্রথম, আদি' },
  { id: 74, arabic: 'الْآخِر',            trans: 'Al-Akhir',           en: 'The Last',                                  bn: 'শেষ, অন্তিম' },
  { id: 75, arabic: 'الظَّاهِر',          trans: 'Az-Zahir',           en: 'The Manifest, The Evident',                 bn: 'প্রকাশমান' },
  { id: 76, arabic: 'الْبَاطِن',          trans: 'Al-Batin',           en: 'The Hidden, The Unmanifest',                bn: 'অপ্রকাশিত, গুপ্ত' },
  { id: 77, arabic: 'الْوَالِي',          trans: 'Al-Wali',            en: 'The Governor, The Ruler',                   bn: 'শাসনকর্তা' },
  { id: 78, arabic: 'الْمُتَعَالِي',      trans: 'Al-Muta\'ali',       en: 'The Self Exalted, The Supreme',             bn: 'সুউচ্চ মহিমান্বিত' },
  { id: 79, arabic: 'الْبَرّ',            trans: 'Al-Barr',            en: 'The Source of Goodness',                    bn: 'কল্যাণকারী' },
  { id: 80, arabic: 'التَّوَّاب',         trans: 'At-Tawwab',          en: 'The Acceptor of Repentance',                bn: 'তওবা কবুলকারী' },
  { id: 81, arabic: 'الْمُنْتَقِم',       trans: 'Al-Muntaqim',        en: 'The Avenger',                               bn: 'প্রতিশোধগ্রহণকারী' },
  { id: 82, arabic: 'الْعَفُوّ',          trans: 'Al-\'Afuww',         en: 'The Pardoner',                              bn: 'ক্ষমাকারী' },
  { id: 83, arabic: 'الرَّؤُوف',          trans: 'Ar-Ra\'uf',          en: 'The Compassionate, The All-Pitying',        bn: 'অতি স্নেহশীল' },
  { id: 84, arabic: 'مَالِكُ الْمُلْك',   trans: 'Malik-ul-Mulk',      en: 'The Owner of all Sovereignty',              bn: 'সর্ব রাজত্বের মালিক' },
  { id: 85, arabic: 'ذُو الْجَلَالِ وَالْإِكْرَام', trans: 'Dhul-Jalali wal-Ikram', en: 'Lord of Majesty and Generosity', bn: 'মহিমা ও মহানুভবতার অধিকারী' },
  { id: 86, arabic: 'الْمُقْسِط',         trans: 'Al-Muqsit',          en: 'The Equitable, The Just',                   bn: 'সুবিচারক' },
  { id: 87, arabic: 'الْجَامِع',          trans: 'Al-Jami\'',          en: 'The Gatherer, The Uniter',                  bn: 'একত্রকারী' },
  { id: 88, arabic: 'الْغَنِيّ',          trans: 'Al-Ghani',           en: 'The Self-Sufficient, The Rich',             bn: 'অভাবমুক্ত' },
  { id: 89, arabic: 'الْمُغْنِي',         trans: 'Al-Mughni',          en: 'The Enricher',                              bn: 'অভাবমোচনকারী' },
  { id: 90, arabic: 'الْمَانِع',          trans: 'Al-Mani\'',          en: 'The Preventer, The Withholder',             bn: 'প্রতিরোধকারী' },
  { id: 91, arabic: 'الضَّار',            trans: 'Ad-Darr',            en: 'The Creator of Harm (in wisdom)',           bn: 'ক্ষতিকারক (হিকমতের সাথে)' },
  { id: 92, arabic: 'النَّافِع',          trans: 'An-Nafi\'',          en: 'The Creator of Good',                       bn: 'উপকারকারী' },
  { id: 93, arabic: 'النُّور',            trans: 'An-Nur',             en: 'The Light',                                 bn: 'জ্যোতি, আলো' },
  { id: 94, arabic: 'الْهَادِي',          trans: 'Al-Hadi',            en: 'The Guide',                                 bn: 'পথপ্রদর্শক' },
  { id: 95, arabic: 'الْبَدِيع',          trans: 'Al-Badi\'',          en: 'The Incomparable, The Originator',          bn: 'অতুলনীয় উদ্ভাবক' },
  { id: 96, arabic: 'الْبَاقِي',          trans: 'Al-Baqi',            en: 'The Everlasting',                           bn: 'চিরস্থায়ী' },
  { id: 97, arabic: 'الْوَارِث',          trans: 'Al-Warith',          en: 'The Ultimate Inheritor',                    bn: 'উত্তরাধিকারী' },
  { id: 98, arabic: 'الرَّشِيد',          trans: 'Ar-Rashid',          en: 'The Guide to the Right Path',               bn: 'সৎপথ প্রদর্শক' },
  { id: 99, arabic: 'الصَّبُور',          trans: 'As-Sabur',           en: 'The Most Patient',                          bn: 'পরম ধৈর্যশীল' },
];
